apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-2jtt
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gnecasov-tenant/devfile-sample-python-basic-1/devfile-sample-python-basic-2jtt@sha256:713ea2c7d076b681a61a2784624675abbe831ece47827b77f0a7fffa9c514c8c
        name: my-python
        resources: {}
status: {}
